// ❗ You don't need to add extra action types to achieve MVP
// export const MOVE_CLOCKWISE = 'MOVE_CLOCKWISE'
// export const MOVE_COUNTERCLOCKWISE = 'MOVE_COUNTERCLOCKWISE'
// export const SET_QUIZ_INTO_STATE = 'SET_QUIZ_INTO_STATE'
// export const SET_SELECTED_ANSWER = 'SET_SELECTED_ANSWER'
// export const SET_INFO_MESSAGE = 'SET_INFO_MESSAGE'
// export const INPUT_CHANGE = 'INPUT_CHANGE'
// export const RESET_FORM = 'RESET_FORM'
export const MOVE_CLOCKWISE = 'MOVE_CLOCKWISE';
export const MOVE_COUNTERCLOCKWISE = 'MOVE_COUNTERCLOCKWISE';
export const SET_QUIZ = 'SET_QUIZ';
export const SET_INFO_MESSAGE = 'SET_INFO_MESSAGE';
export const SELECT_ANSWER = 'SELECT_ANSWER';
export const SET_NEW_QUESTION = 'SET_NEW_QUESTION';
export const SET_NEW_TRUE_ANSWER = 'SET_NEW_TRUE_ANSWER';
export const SET_NEW_FALSE_ANSWER = 'SET_NEW_FALSE_ANSWER';
export const CREATE_QUIZ_SUCCESS = 'CREATE_QUIZ_SUCCESS';